# Generated by Django 5.2 on 2025-05-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date',
            new_name='date_of_birth',
        ),
    ]
