# Generated by Django 4.2.22 on 2025-06-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
