# Generated by Django 4.2.22 on 2025-06-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_delete_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
