# Generated by Django 4.2.22 on 2025-06-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_video_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='video',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
