# Generated by Django 4.2.22 on 2025-06-27 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0011_remove_story_image_storyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyimage',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
