# Generated by Django 4.2.22 on 2025-06-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_storyimage_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories/videos/'),
        ),
    ]
