# Generated by Django 4.2.22 on 2025-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_storyimage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
