# Generated by Django 4.2.22 on 2025-06-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_image_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='autoplay',
            field=models.BooleanField(default=True),
        ),
    ]
